-- Rename GOVERNANCE_CHECK to GOVERNANCE in AdminRole enum
ALTER TYPE "AdminRole" RENAME VALUE 'GOVERNANCE_CHECK' TO 'GOVERNANCE';

-- Rename audit action
ALTER TYPE "AuditAction" RENAME VALUE 'ONBOARD_REQUEST_SUBMITTED_TO_GOVERNANCE_CHECK' TO 'ONBOARD_REQUEST_SUBMITTED_TO_GOVERNANCE';
