-- Rename LEGAL to GOVERNANCE_CHECK across all enums and columns
ALTER TYPE "AdminRole" RENAME VALUE 'LEGAL' TO 'GOVERNANCE_CHECK';
ALTER TYPE "OnboardRequestStatus" RENAME VALUE 'PENDING_LEGAL' TO 'PENDING_GOVERNANCE_CHECK';
ALTER TYPE "AuditAction" RENAME VALUE 'ONBOARD_REQUEST_SUBMITTED_TO_LEGAL' TO 'ONBOARD_REQUEST_SUBMITTED_TO_GOVERNANCE_CHECK';
ALTER TABLE "OnboardRequestApproval" RENAME COLUMN "legalScore" TO "governanceScore";
